routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

// Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::post('/locale', 'PagesController@changelocale')->name('locale');

//Routes to the index function to landing page.
Route::get('/', 'PagesController@index');

//Creates all the routes to the 'CRUD' functions in the events' controller.
Route::resource('/events', 'EventsController');

//Routes to the members function to members page.
Route::get('/members', 'PagesController@members');

//Routes to the user account function to the user's page. [Needs to a handle for userID]
Route::get('/myaccount', 'PagesController@myaccount');

//Creates all the routes to the 'CRUD' functions in the articles' controller.
Route::resource('articles', 'ArticlesController');

//Creates all the routes to the 'CRUD' functions in the users' controller.
Route::resource('users', 'UsersController');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::post('users/{id}', 'DashboardController@createRequest')->name('dashboard.createRequest');

Route::post('dashboard/{id?}/accept', 'DashboardController@acceptRequest')->name('dashboard.acceptRequest');

Route::post('dashboard/{id?}/reject', 'DashboardController@rejectRequest')->name('dashboard.rejectRequest');

Route::get('events/archive/{id}/edit', 'EventsController@archiveEventShow')->name('events.archiveEventShow');

Route::post('events/archive/{id}', 'EventsController@archiveEvent')->name('events.archiveEvent');

app/User.php
<?php

namespace App;

use App\Filters\UserFilter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fName',
        'lName',
        'bDate',
        'sex',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function articles(){
        return $this->hasMany('App\Article', 'authorID');
    }

    public function events(){
        return $this->hasMany('App\Event', 'userID');
    }

    public function userCredentials(){
        return $this->hasMany('App\UserCredential', 'userID');
    }

    public function userReferences(){
        return $this->hasMany('App\UserReference', 'userID');
    }

    public function scopeSearch($query, $q){
        if($q == null)
        {
            return $query;
        }
        return $query->where('fName', 'LIKE', "%{$q}%")
                     ->orWhere('lName', 'LIKE', "%{$q}%")
                     ->orWhere('email', 'LIKE', "%{$q}%");
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\UserCredential;
use App\UserReference;
use DateTime;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Date;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;
use Redirect,Response,DB,Config;
use Intervention\Image\Facades\Image;
use Ramsey\Uuid\Type\Integer;

class UsersController extends Controller
{
        /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        // if($request()->ajax())
        // {
        //     if(!empty($request->filter_sex))
        //     {
        //         $data = User::where('sex', $request->filter_sex)->get();
        //     }
        //     else if(!empty($request->filter_category))
        //     {
        //         $data = User::where('previllage', $request->filter_category)->get();
        //     }
        //     else
        //     {
        //         $data = User::filter($request)->latest()->paginate(10);
        //     }
        //     return $data;
        // }

        $search_string = null;
        $category = null;
        $age = null;
        $sex = null;

        if($request->has('search_string'))
        {
            $search_string = $request->query('search_string');
            $users = User::search($search_string)->latest()->paginate(10);
        }
        if($request->has('category'))
        {
            $category = $request->query('category');
            $users = User::search($category)->latest()->paginate(10);
        }
        if($request->has('age'))
        {
            $age = $request->query('age');
            $users = User::search($age)->latest()->paginate(10);
        }
        if($request->has('sex'))
        {
            $sex = $request->query('sex');
            $users = User::search($sex)->latest()->paginate(10);
        }
        else
        {
            $users = User::latest()->paginate(10);
        }

        // $userIds = array('');

        // for($i = 0; $i < sizeof($users); $i++){
        //     $userIds = array_push($userIds, $users[$i]->id);
        // }

        // $userCredentials = array('' => new UserCredential, );

        // for($i = 0; $i < sizeof($users); $i++){
            $userCredentials = UserCredential::whereIn('userID', User::latest()->paginate(10)->pluck('id'))->orderBy('id', 'desc')->get();
        // }
        return view('users.users')->with('users', $users)
                                  ->with('userCredentials', $userCredentials)
                                  ->with('search_string', $search_string)
                                  ->with('category', $category)
                                  ->with('age', $age)
                                  ->with('sex', $sex);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $user = User::find($id);
        $userCredential = UserCredential::where('userID', $id)->first();
        $userReference = UserReference::where('userID', $id)->first();

        $BoD = $user->bDate;
        $BoD = new DateTime($BoD);
        $dif = $BoD->diff(new DateTime());
        $age = $dif->y;
        return view('users.show')->with('user', $user)->with('userCredential', $userCredential)->with('userReference', $userReference)->with('age', $age);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);
        $userCredential = UserCredential::where('userID', $id)->first();
        $userReference = UserReference::where('userID', $id)->first();

        //Checking for the correct user
        if(auth()->user()->id != $user->id){
            return redirect('/users')->with('error', 'Unauthorized Access');
        }

        $userData = [
            $user,
            $userCredential,
            $userReference
        ];

        return view('users.edit')->with('user', $user)->with('userCredential', $userCredential)->with('userReference', $userReference);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            //Set validation restrictions for the input parameters
            'fName' => 'required',
            'lName' => 'required',
            'bDate' => 'required',
            'sex' => 'required',
            'userProfilePic' => 'image|nullable|max:5000|mimes:png,jpg,jpeg,bmp,svg',
            'frontHeadshot' => 'required|image|max:5000|mimes:png,jpg,jpeg,bmp,svg',
            'leftHeadshot' => 'image|nullable|max:5000|mimes:png,jpg,jpeg,bmp,svg',
            'rightHeadshot' => 'image|nullable|max:5000|mimes:png,jpg,jpeg,bmp,svg',
            'email' => 'required',
            // 'password' => 'required',
            'educationalBackground' => 'required',
            'occupation' => 'required',
            'fieldOfExpertise' => 'required',
            'fieldOfInterest' => 'required',
        ]);

        /* Fetch user's profile picture */
        // Handle the profile picture image upload
        if($request -> hasFile('userProfilePic')){

            $upp = $request->file('userProfilePic');
            $filenameWithExt = $upp->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $fileExtension = $upp->getClientOriginalExtension();
            $UPCfilenameToStore = 'UPC'.'_'.$filename.'_'.time().'.'.$fileExtension;
            Image::make($upp)->resize(300, 300)->save(public_path('/storage/userPPs/').$UPCfilenameToStore);
        }
        else{
            $UPCfilenameToStore = 'UPC_noimage.jpg';
        }

        // Handle the headshot images upload
        if($request -> hasFile('frontHeadshot')){
            $fhs = $request->file('frontHeadshot');
            $filenameWithExt = $fhs->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $fileExtension = $fhs->getClientOriginalExtension();
            $FHSfilenameToStore = 'FHS'.'_'.$filename.'_'.time().'.'.$fileExtension;
            Image::make($fhs)->resize(300, 300)->save(public_path('/storage/userHeadshots/').$FHSfilenameToStore);
        }
        else{
            $FHSfilenameToStore = 'FHS_noimage.jpg';
        }

        if($request -> hasFile('leftHeadshot')){
            $lhs = $request->file('leftHeadshot');
            $filenameWithExt = $lhs->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $fileExtension = $lhs->getClientOriginalExtension();
            $LHSfilenameToStore = 'FHS'.'_'.$filename.'_'.time().'.'.$fileExtension;
            Image::make($lhs)->resize(300, 300)->save(public_path('/storage/userHeadshots/').$LHSfilenameToStore);
        }
        else{
            $LHSfilenameToStore = 'LHS_noimage.jpg';
        }

        if($request -> hasFile('rightHeadshot')){
            $rhs = $request->file('rightHeadshot');
            $filenameWithExt = $rhs->getClientOriginalName();
            $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
            $fileExtension = $rhs->getClientOriginalExtension();
            $RHSfilenameToStore = 'FHS'.'_'.$filename.'_'.time().'.'.$fileExtension;
            Image::make($rhs)->resize(300, 300)->save(public_path('/storage/userHeadshots/').$RHSfilenameToStore);
        }
        else{
            $RHSfilenameToStore = 'RHS_noimage.jpg';
        }

        // Create a user object
        $user = User::find($id);

        // Create a user creadential object
        $userCredential = UserCredential::where('userID', $id)->first();
        $userReference = UserReference::where('userID', $id)->first();

        // Fetch user's first name
        $user->fName = $request->input('fName');

        $user->lName = $request->input('lName');

        $user->bDate = $request->input('bDate');

        $user->sex = $request->input('sex');

        $user->email = $request->input('email');

        $user->userProfilePic = $UPCfilenameToStore;

        $user->frontHeadshot = $FHSfilenameToStore;

        $user->leftHeadshot = $LHSfilenameToStore;

        $user->rightHeadshot = $RHSfilenameToStore;

        $userCredential->educationalBackground = $request->input('educationalBackground');

        $userCredential->occupation = $request->input('occupation');

        $userCredential->fieldOfExpertise = $request->input('fieldOfExpertise');

        $userCredential->fieldOfInterest = $request->input('fieldOfInterest');

        $user->save();

        $userCredential->save();

        $userReference->save();

        return redirect('/dashboard')->with('success', 'Profile Updated Successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::find($id);

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container mt-4">
        <h1>Edit Profile</h1>
        <div class="container">
            {!! Form::open(['action' => ['UsersController@update', $user->id], 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
                <!-- User Fullname Input Field -->
                <div class="form-group">
                    {{ Form::label('fName', 'First name') }}
                    {{ Form::text('fName', $user->fName, ['class' => 'form-control', 'placeholder' => 'Your First Name']) }}
                </div>

                <div class="form-group">
                    {{ Form::label('lName', 'Last name') }}
                    {{ Form::text('lName', $user->lName, ['class' => 'form-control', 'placeholder' => 'Your Last Name']) }}
                </div>

                <!-- User Birth Date Input Field -->
                <div class="form-group">
                    {{ Form::label('bDate', 'Birth date') }}
                    {{ Form::date('bDate', $user->bDate, ['class' => 'form-control, date', 'type' => 'date', 'placeholder' => 'Your Birthdate']) }}
                </div>

                <!-- User Sex -->
                <div class="form-group">
                    {{ Form::label('sex', 'Gender') }}
                    {{ Form::text('sex', $user->sex, ['class' => 'form-control', 'placeholder' => 'Your Sexual Orientation']) }}
                </div>

                <!-- User Email -->
                <div class="form-group">
                    {{ Form::label('emal', 'Email') }}
                    {{ Form::text('email', $user->email, ['class' => 'form-control', 'type' => 'email', 'placeholder' => 'Your Email']) }}
                </div>

                <!-- User Profile Picture -->
                <div class="form-group">
                    <div class="custom-file">
                        {{ Form::label('userProfilePic', 'Profile Picture') }}
                        {{ Form::file('userProfilePic'), $user->userProfilePic }}
                    </div>
                </div>

                <!-- User Headshots -->
                <div class="form-group">
                    {{-- <div class="custom-file"> --}}
                        {{ Form::label('frontHeadshot', 'Frontal Headshot') }}
                        {{ Form::file('frontHeadshot'), $user->frontHeadshot }}
                    {{-- </div> --}}
                </div>

                <div class="form-group">
                    <div class="custom-file">
                        {{ Form::label('leftHeadshot', 'Left Headshot') }}
                        {{ Form::file('leftHeadshot') }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="custom-file">
                        {{ Form::label('rightHeadshot', 'Right Headshot') }}
                        {{ Form::file('rightHeadshot') }}
                    </div>
                </div>

                <!-- User Educational Background -->
                <div class="form-group">
                    {{ Form::label('educationalBackground', 'Educational Background') }}
                    {{ Form::text('educationalBackground', $userCredential->educationalBackground, ['class' => 'form-control', 'placeholder' => 'Your Educational Background']) }}
                </div>

                <!-- User Occupation -->
                <div class="form-group">
                    {{ Form::label('occupation', 'Occupation') }}
                    {{ Form::text('occupation', $userCredential->occupation, ['class' => 'form-control', 'placeholder' => 'Your Occupation']) }}
                </div>

                <!-- User Field of Expertise -->
                <div class="form-group">
                    {{ Form::label('fieldOfExpertise', 'Field of Expertise') }}
                    {{ Form::text('fieldOfExpertise', $userCredential->fieldOfExpertise, ['class' => 'form-control', 'placeholder' => 'Your Field of Expertise']) }}
                </div>

                <!-- User Field of Interest -->
                <div class="form-group">
                    {{ Form::label('fieldOfInterest', 'Field of Interest') }}
                    {{ Form::text('fieldOfInterest', $userCredential->fieldOfInterest, ['class' => 'form-control', 'placeholder' => 'Your Field of Interest']) }}
                </div>

                <!--Spoof a PUT request from a POST method.-->
                {{Form::hidden('_method', 'PUT')}}

                {{Form::submit('Submit', ['class' => 'btn btn-primary'])}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="row mt-5 justify-content-center">
        <img style="width:150px !important; height:150px !important; float:center !important; border-radius: 50% !important; margin-right: auto !important; margin-left: auto !important;" src="/storage/userPPs/{{$user->userProfilePic}}" alt="{{$user->fName}} {{$user->lName}}'s Profile Picture">
    </div>

    <div class="row my-5 justify-content-center">
        <h3> {{ $user->fName }} {{ $user->lName }} </h3>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-auto">
                <div class="card">
                    <img class="card-img" src="/storage/userHeadshots/{{$user->leftHeadshot}}" style="width: 150px; height:200px; border-radius:20px;" alt="Left Headshot">
                </div>
            </div>

            <div class="col-md-auto">
                <div class="card">
                    <img class="card-img" src="/storage/userHeadshots/{{$user->frontHeadshot}}" style="width: 150px; height:200px; border-radius:20px;" alt="Front Headshot">
                </div>
            </div>

            <div class="col-md-auto">
                <div class="card">
                    <img class="card-img" src="/storage/userHeadshots/{{$user->rightHeadshot}}" style="width: 150px; height:200px; border-radius:20px;" alt="Right Headshot">
                </div>
            </div>
        </div>
    </div>

    <div class="container justify-content-center">
        <p class="">Age: {{$age}} </p>
        <p class="">Gender: {{$user->sex}}</p>
        <p class="">Occupation: {{$userCredential->occupation}}</p>
        <p class="">Field of Expertise: {{$userCredential->fieldOfExpertise}}</p>
        <p class="">Field of Interest: {{$userCredential->fieldOfInterest}}</p>
    </div>
    <hr>
    @if(!Auth::guest())
        <div class="container">
            {!! Form::open(['action' => ['DashboardController@createRequest', $user->id], 'method' => 'POST']) !!}
                {{ Form::submit('Request Contact Info', ['class' => 'btn btn-sm btn-primary']) }}
            {!! Form::close() !!}
            {{-- <form action="{{ route('dashboard.createRequest', $user->id) }}" method="POST">
                <button class="btn btn-sm btn-primary" type="submit">Request Contact Info</button>
            </form> --}}
        </div>
        @if(Auth::user()->id == $user->id)
            <div class="container">
                <a href="/users/{{$user->id}}/edit" class="btn btn-outline-secondary">Edit</a>

                {!! Form::open(['action' => ['UsersController@destroy', $user->id], 'method' => 'POST', 'class' => 'inline pull-right float-right mr-md-5']) !!}
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::submit('Delete', ['class' => 'btn btn-danger float-right', 'onClick' => "return confirm('Are you sure?')"]) }}
                {!! Form::close() !!}
            </div>
        @endif

        @if (Auth::user()->previllage == 'Admin')
            <div class="container">
                {!! Form::open(['action' => ['UsersController@destroy', $user->id], 'method' => 'POST', 'class' => '']) !!}
                    {{ Form::hidden('_method', 'DELETE') }}
                    {{ Form::submit('Delete', ['class' => 'btn btn-danger ml-md-auto mr-md-5', 'onClick' => "return confirm('Are you sure?')"]) }}
                {!! Form::close() !!}
            </div>
        @endif
    @endif
@endsection

resources/views/users/userlist.blade.php
@extends('layouts.app')

@section('content')
<div class="container my-md-4">
    <!--Session check-->
    @if (session('status'))
        <div class="alert alert-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <table class="table table-hover">
        <tr>
            <th>Name</th>
        </tr>
    </table>
@endsection

resources/views/users/users.blade.php
@extends('layouts.app')

@section('content')
    <!-- Members Page Cover -->
    {{-- <div class="article-jumbotron">
        <div class="mx-5 py-3">
            <h1 class="mb-md-4">Members</h1>
            <div class="ml-md-3">
                <h5>Filter by:</h5>
                <div class="row align-items-lg-end">
                    <div class="col-md-3 justify-content-md-start">
                        <form action="{{ route('users.index') }}">
                            <select name="category" id="category" class="form-control form-control-sm" value="{{ $category }}" (change)="{{ route('users.index') }}">
                                <option value="">Category</option>
                                <option value="actor">Actor</option>
                                <option value="director">Director</option>
                                <option value="producer">Producer</option>
                                <option value="camera">Camera Operator</option>
                            </select>
                        </form>

                    </div>
                    <div class="col-md-3 justify-content-md-start">
                        <select name="filter-sex" id="filter_sex" class="form-control form-control-sm" value="{{ $sex }}" (change)="{{ route('users.index') }}">
                            <option value="">Gender</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                        </select>
                    </div> --}}
                    {{--<div class="col-md-3">
                        <div class="form-row form-group">
                            <button type="button" name="filter" id="filter" class="col-md-6 btn btn-primary">Filter</button>
                            <button type="button" name="reset" id="reset" class="col-md-6 btn btn-default">Reset</button>
                        </div>
                    </div> --}}
                    {{-- <div class="col-md-6 align-self-md-end">
                        <div class="ml-4 align-self-md-end">
                            <form action="{{ route('users.index') }}">
                                <div class="row align-self-md-end">
                                    <div class="col-md-9 form-group align-self-md-end">
                                        <label for="search_string" class="">Search</label>
                                        <input type="search" name="search_string" value="{{ $search_string }}" class="form-control form-control-sm" placeholder="Search with a keyword here ...">
                                    </div>
                                    <div class="col-md-3 align-self-md-center align-self-md-end">
                                        <button type="submit" class="btn btn-sm btn-info">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> --}}
    <!-- Members are in chronological order, with the latest showing first -->
    <div class="m-5 px-5 py-4">
        @if(count($users) > 0 && isset($users))
            @foreach ($users as $user)
                <div class="well">
                    <div class="mb-md-5 pb-md-2">
                        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col-8 d-none d-lg-block ml-md-4 pr-md-2 my-md-3">
                                <h4 class="font-weight-bold">{{$user->fName}} {{$user->lName}}</h4>
                                {{-- {{ count($userCredentials) }} --}}
                                {{-- {{ $userCredentials }} --}}
                                {{-- {{ $users[0] }} --}}
                                {{-- {{ $userCredentials[0] }} --}}
                                @foreach ($userCredentials as $userCredential)
                                    @if ($userCredential->userID == $user->id)
                                    <p class="card-text mb-auto">Talent: {{$userCredential->fieldOfExpertise}}</p>
                                    @endif
                                @endforeach
                                <div class="mt-2">
                                    <a href="/users/{{$user->id}}" class="stretched-link">View Detail</a>
                                </div>
                                {{-- <div class="mt-3 float-md-right">
                                    @if (Auth::user()->previllage == 'Admin')
                                        <div class="container">
                                            {!! Form::open(['action' => ['UsersController@destroy', $user->id], 'method' => 'POST', 'class' => 'inline pull-right float-right mr-md-4']) !!}
                                                {{ Form::hidden('_method', 'DELETE') }}
                                                {{ Form::submit('Delete', ['class' => 'btn btn-danger float-right', 'onClick' => "return confirm('Are you sure?')"]) }}
                                            {!! Form::close() !!}
                                        </div>
                                    @endif
                                </div> --}}
                            </div>

                            <div class="col d-flex flex-column position-static">
                                <img style="min-width: 30% !important; max-width: 40% !important;" class="rounded mr-0 float-right" src="/storage/userPPs/{{$user->userProfilePic}}">
                                {{-- <svg class="bd-placeholder-img" width="361" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg> --}}
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach

            <!--Pagination-->
            <div class="row text-center">
                {{$users->links()}}
            </div>

            @else
            <div class="badge-warning">
                <p>No users found.</p>
            </div>
        @endif
    </div>
@endsection